# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/cucumber-core/all/cucumber-core.rbi
#
# cucumber-core-3.2.1

module Cucumber
end
module Cucumber::Core
  def compile(gherkin_documents, last_receiver, filters = nil, event_bus = nil); end
  def compose(filters, last_receiver); end
  def execute(gherkin_documents, filters = nil, event_bus = nil); end
  def parse(gherkin_documents, compiler, event_bus); end
end
class Cucumber::Core::Event
  def self.event_id; end
  def self.new(*attributes); end
  def self.underscore(string); end
end
module Cucumber::Core::Events
  def self.build_registry(*types); end
  def self.registry; end
end
class Anonymous_Cucumber_Core_Event_4 < Cucumber::Core::Event
  def attributes; end
  def event_id; end
  def gherkin_document; end
  def initialize(*args); end
  def to_h; end
  def uri; end
end
class Cucumber::Core::Events::GherkinSourceParsed < Anonymous_Cucumber_Core_Event_4
  def gherkin_document; end
  def uri; end
end
class Anonymous_Cucumber_Core_Event_5 < Cucumber::Core::Event
  def attributes; end
  def event_id; end
  def initialize(*args); end
  def test_case; end
  def to_h; end
end
class Cucumber::Core::Events::TestCaseStarted < Anonymous_Cucumber_Core_Event_5
  def test_case; end
end
class Anonymous_Cucumber_Core_Event_6 < Cucumber::Core::Event
  def attributes; end
  def event_id; end
  def initialize(*args); end
  def test_step; end
  def to_h; end
end
class Cucumber::Core::Events::TestStepStarted < Anonymous_Cucumber_Core_Event_6
  def test_step; end
end
class Anonymous_Cucumber_Core_Event_7 < Cucumber::Core::Event
  def attributes; end
  def event_id; end
  def initialize(*args); end
  def result; end
  def test_step; end
  def to_h; end
end
class Cucumber::Core::Events::TestStepFinished < Anonymous_Cucumber_Core_Event_7
  def result; end
  def test_step; end
end
class Anonymous_Cucumber_Core_Event_8 < Cucumber::Core::Event
  def attributes; end
  def event_id; end
  def initialize(*args); end
  def result; end
  def test_case; end
  def to_h; end
end
class Cucumber::Core::Events::TestCaseFinished < Anonymous_Cucumber_Core_Event_8
  def result; end
  def test_case; end
end
class Cucumber::Core::EventBus
  def broadcast(event); end
  def broadcast_queued_events_to(handler, event_type); end
  def event_types; end
  def handlers_for(event_class); end
  def initialize(registry = nil); end
  def is_registered_id?(event_id); end
  def is_registered_type?(event_type); end
  def method_missing(event_id, *args); end
  def on(event_id, handler_object = nil, &handler_proc); end
  def validate_handler_and_event_id!(handler, event_id); end
end
module Cucumber::Core::Test
end
module Cucumber::Core::Test::Result
  def self.ok?(type, be_strict = nil); end
  def self.query_methods(result_type); end
end
class Cucumber::Core::Test::Result::Unknown
  def describe_to(visitor, *args); end
  def with_filtered_backtrace(filter); end
  include Anonymous_Module_9
end
module Anonymous_Module_9
  def failed?; end
  def flaky?; end
  def passed?; end
  def pending?; end
  def skipped?; end
  def to_sym; end
  def undefined?; end
  def unknown?; end
end
class Cucumber::Core::Test::Result::Passed
  def describe_to(visitor, *args); end
  def duration; end
  def duration=(arg0); end
  def initialize(duration); end
  def ok?(be_strict = nil); end
  def self.ok?(be_strict = nil); end
  def to_s; end
  def with_appended_backtrace(step); end
  def with_filtered_backtrace(filter); end
  include Anonymous_Module_10
end
module Anonymous_Module_10
  def failed?; end
  def flaky?; end
  def passed?; end
  def pending?; end
  def skipped?; end
  def to_sym; end
  def undefined?; end
  def unknown?; end
end
class Cucumber::Core::Test::Result::Failed
  def describe_to(visitor, *args); end
  def duration; end
  def exception; end
  def initialize(duration, exception); end
  def ok?(be_strict = nil); end
  def self.ok?(be_strict = nil); end
  def to_s; end
  def with_appended_backtrace(step); end
  def with_duration(new_duration); end
  def with_filtered_backtrace(filter); end
  include Anonymous_Module_11
end
module Anonymous_Module_11
  def failed?; end
  def flaky?; end
  def passed?; end
  def pending?; end
  def skipped?; end
  def to_sym; end
  def undefined?; end
  def unknown?; end
end
class Cucumber::Core::Test::Result::Flaky
  def self.ok?(be_strict = nil); end
end
class Cucumber::Core::Test::Result::Raisable < StandardError
  def duration; end
  def initialize(message = nil, duration = nil, backtrace = nil); end
  def message; end
  def ok?(be_strict = nil); end
  def with_appended_backtrace(step); end
  def with_duration(new_duration); end
  def with_filtered_backtrace(filter); end
  def with_message(new_message); end
end
class Cucumber::Core::Test::Result::Undefined < Cucumber::Core::Test::Result::Raisable
  def describe_to(visitor, *args); end
  def self.ok?(be_strict = nil); end
  def to_s; end
  include Anonymous_Module_12
end
module Anonymous_Module_12
  def failed?; end
  def flaky?; end
  def passed?; end
  def pending?; end
  def skipped?; end
  def to_sym; end
  def undefined?; end
  def unknown?; end
end
class Cucumber::Core::Test::Result::Skipped < Cucumber::Core::Test::Result::Raisable
  def describe_to(visitor, *args); end
  def self.ok?(be_strict = nil); end
  def to_s; end
  include Anonymous_Module_13
end
module Anonymous_Module_13
  def failed?; end
  def flaky?; end
  def passed?; end
  def pending?; end
  def skipped?; end
  def to_sym; end
  def undefined?; end
  def unknown?; end
end
class Cucumber::Core::Test::Result::Pending < Cucumber::Core::Test::Result::Raisable
  def describe_to(visitor, *args); end
  def self.ok?(be_strict = nil); end
  def to_s; end
  include Anonymous_Module_14
end
module Anonymous_Module_14
  def failed?; end
  def flaky?; end
  def passed?; end
  def pending?; end
  def skipped?; end
  def to_sym; end
  def undefined?; end
  def unknown?; end
end
class Cucumber::Core::Test::Result::StrictConfiguration
  def initialize(strict_types = nil); end
  def merge!(other); end
  def set?(type); end
  def set_strict(setting, type = nil); end
  def settings; end
  def settings=(arg0); end
  def strict?(type = nil); end
end
class Cucumber::Core::Test::Result::Summary
  def decrement_failed; end
  def duration(duration); end
  def durations; end
  def exception(exception); end
  def exceptions; end
  def get_total(method_name); end
  def increment_total(status); end
  def initialize; end
  def method_missing(name, *args); end
  def ok?(be_strict = nil); end
  def total(for_status = nil); end
end
class Cucumber::Core::Test::Result::Duration
  def initialize(nanoseconds); end
  def nanoseconds; end
end
class Cucumber::Core::Test::Result::UnknownDuration
  def nanoseconds; end
  def tap(&block); end
end
module Cucumber::Core::Ast
end
class Cucumber::Core::Ast::IncompatibleLocations < StandardError
end
module Cucumber::Core::Ast::Location
  def self.from_file_colon_line(file_colon_line); end
  def self.from_source_location(file, line); end
  def self.merge(*locations); end
  def self.new(file, raw_lines = nil); end
  def self.of_caller(additional_depth = nil); end
end
class Anonymous_Struct_15 < Struct
  def file; end
  def file=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Cucumber::Core::Ast::Location::Wildcard < Anonymous_Struct_15
  def include?(lines); end
  def match?(other); end
  def to_s; end
end
class Anonymous_Struct_16 < Struct
  def file; end
  def file=(_); end
  def lines; end
  def lines=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Cucumber::Core::Ast::Location::Precise < Anonymous_Struct_16
  def +(other); end
  def hash; end
  def include?(other_lines); end
  def inspect; end
  def line; end
  def match?(other); end
  def on_line(new_line); end
  def to_s; end
  def to_str; end
end
class Anonymous_Struct_17 < Struct
  def data; end
  def data=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.members; end
  def self.new(*arg0); end
end
class Cucumber::Core::Ast::Location::Lines < Anonymous_Struct_17
  def +(more_lines); end
  def data; end
  def first; end
  def include?(other); end
  def initialize(raw_data); end
  def inspect; end
  def range?; end
  def to_s; end
end
module Cucumber::Core::Ast::HasLocation
  def all_locations; end
  def attributes; end
  def comments; end
  def file; end
  def file_colon_line; end
  def line; end
  def location; end
  def multiline_arg; end
  def tags; end
end
module Cucumber::Core::Filter
  def self.new(*attributes, &block); end
end
module Cucumber::Core::Ast::DescribesItself
  def describe_to(visitor, *args); end
end
class Cucumber::Core::Ast::Comment
  def initialize(location, value); end
  def inspect; end
  def location; end
  def to_s; end
  def value; end
  include Cucumber::Core::Ast::HasLocation
end
class Cucumber::Core::Ast::Tag
  def initialize(location, name); end
  def inspect; end
  def name; end
  include Cucumber::Core::Ast::HasLocation
end
module Cucumber::Core::Ast::Names
  def description; end
  def inspect; end
  def legacy_conflated_name_and_description; end
  def name; end
  def to_s; end
end
class Cucumber::Core::Ast::Feature
  def background; end
  def children; end
  def comments; end
  def description; end
  def description_for_visitors; end
  def feature_elements; end
  def initialize(language, location, comments, tags, keyword, name, description, feature_elements); end
  def keyword; end
  def language; end
  def location; end
  def short_name; end
  def tags; end
  include Cucumber::Core::Ast::DescribesItself
  include Cucumber::Core::Ast::HasLocation
  include Cucumber::Core::Ast::Names
end
class Cucumber::Core::Ast::NullFeature
  def method_missing(*args, &block); end
end
class Cucumber::Core::Ast::BackgroundFinder
  def background(background); end
  def initialize(feature_elements); end
  def method_missing(*arg0); end
  def result; end
end
class Cucumber::Core::Ast::LanguageDelegator < SimpleDelegator
  def initialize(iso_code, obj); end
  def iso_code; end
end
class Cucumber::Core::Ast::EmptyBackground
  def describe_to(*arg0); end
  def inspect; end
end
class Cucumber::Core::Ast::EmptyMultilineArgument
  def all_locations; end
  def data_table?; end
  def describe_to(*arg0); end
  def doc_string?; end
  def inspect; end
  def map(&block); end
end
class Cucumber::Core::Ast::Background
  def children; end
  def comments; end
  def description; end
  def description_for_visitors; end
  def initialize(location, comments, keyword, name, description, raw_steps); end
  def keyword; end
  def location; end
  def raw_steps; end
  include Cucumber::Core::Ast::DescribesItself
  include Cucumber::Core::Ast::HasLocation
  include Cucumber::Core::Ast::Names
end
class Cucumber::Core::Ast::Scenario
  def background; end
  def children; end
  def comments; end
  def description; end
  def description_for_visitors; end
  def initialize(location, comments, tags, keyword, name, description, steps); end
  def keyword; end
  def location; end
  def raw_steps; end
  def tags; end
  include Cucumber::Core::Ast::DescribesItself
  include Cucumber::Core::Ast::HasLocation
  include Cucumber::Core::Ast::Names
end
class Cucumber::Core::Ast::Step
  def actual_keyword(previous_step_keyword = nil); end
  def backtrace_line; end
  def children; end
  def comments; end
  def description_for_visitors; end
  def exception; end
  def initialize(language, location, comments, keyword, text, multiline_arg); end
  def inspect; end
  def keyword; end
  def language; end
  def multiline_arg; end
  def original_location; end
  def text; end
  def to_s; end
  include Cucumber::Core::Ast::DescribesItself
  include Cucumber::Core::Ast::HasLocation
end
class Cucumber::Core::Ast::ExpandedOutlineStep < Cucumber::Core::Ast::Step
  def all_locations; end
  def backtrace_line; end
  def initialize(outline_step, language, location, comments, keyword, text, multiline_arg); end
  def original_location; end
  def step_backtrace_line; end
end
class Cucumber::Core::Ast::DocString < SimpleDelegator
  def ==(other); end
  def content; end
  def content_type; end
  def data_table?; end
  def description_for_visitors; end
  def doc_string?; end
  def initialize(content, content_type, location); end
  def inspect; end
  def map; end
  def to_step_definition_arg; end
  include Cucumber::Core::Ast::DescribesItself
  include Cucumber::Core::Ast::HasLocation
end
class Cucumber::Core::Ast::DataTable
  def ==(other); end
  def data_table?; end
  def description_for_visitors; end
  def doc_string?; end
  def dup; end
  def ensure_array_of_array(array); end
  def hashes_to_array(hashes); end
  def initialize(rows, location); end
  def inspect; end
  def map(&block); end
  def raw; end
  def to_step_definition_arg; end
  def transpose; end
  def verify_rows_are_same_length(raw); end
  include Cucumber::Core::Ast::DescribesItself
  include Cucumber::Core::Ast::HasLocation
end
class Cucumber::Core::Ast::ScenarioOutline
  def children; end
  def comments; end
  def description_for_visitors; end
  def examples_tables; end
  def initialize(location, comments, tags, keyword, name, description, steps, examples); end
  def keyword; end
  def line; end
  def steps; end
  def tags; end
  include Cucumber::Core::Ast::DescribesItself
  include Cucumber::Core::Ast::HasLocation
  include Cucumber::Core::Ast::Names
end
class Cucumber::Core::Ast::ScenarioOutline::MissingExamples < StandardError
end
class Cucumber::Core::Ast::OutlineStep
  def children; end
  def comments; end
  def description_for_visitors; end
  def initialize(language, location, comments, keyword, text, multiline_arg); end
  def inspect; end
  def keyword; end
  def language; end
  def location; end
  def multiline_arg; end
  def replace_multiline_arg(example_row); end
  def text; end
  def to_s; end
  def to_step(row); end
  include Cucumber::Core::Ast::DescribesItself
  include Cucumber::Core::Ast::HasLocation
end
class Cucumber::Core::Ast::ExamplesTable
  def children; end
  def comments; end
  def description_for_visitors; end
  def example_rows; end
  def header; end
  def initialize(location, comments, tags, keyword, name, description, header, example_rows); end
  def keyword; end
  def location; end
  def tags; end
  include Cucumber::Core::Ast::DescribesItself
  include Cucumber::Core::Ast::HasLocation
  include Cucumber::Core::Ast::Names
end
class Cucumber::Core::Ast::ExamplesTable::Header
  def build_row(row_cells, number, location, language, comments); end
  def comments; end
  def initialize(cells, location, comments); end
  def inspect; end
  def values; end
  include Cucumber::Core::Ast::HasLocation
end
class Cucumber::Core::Ast::ExamplesTable::Row
  def ==(other); end
  def [](parameter_name); end
  def comments; end
  def data; end
  def description_for_visitors; end
  def expand(string); end
  def initialize(data, number, location, language, comments); end
  def inspect; end
  def language; end
  def number; end
  def values; end
  include Cucumber::Core::Ast::DescribesItself
  include Cucumber::Core::Ast::HasLocation
end
class Cucumber::Core::Ast::Examples < Cucumber::Core::Ast::ExamplesTable
end
module Cucumber::Core::Gherkin
end
class Cucumber::Core::Gherkin::AstBuilder
  def feature(attributes); end
  def file; end
  def initialize(uri); end
end
class Cucumber::Core::Gherkin::AstBuilder::Builder
  def attributes; end
  def children; end
  def comments; end
  def description; end
  def file; end
  def handle_comments(comments); end
  def initialize(file, attributes); end
  def keyword; end
  def line; end
  def location; end
  def name; end
  def rubify_keys(hash); end
  def tags; end
  def underscore(string); end
end
class Cucumber::Core::Gherkin::AstBuilder::DocumentBuilder < Cucumber::Core::Gherkin::AstBuilder::Builder
  def all_comments; end
  def feature; end
  def initialize(file, attributes); end
end
class Cucumber::Core::Gherkin::AstBuilder::FeatureBuilder < Cucumber::Core::Gherkin::AstBuilder::Builder
  def children; end
  def feature_element_builders; end
  def feature_elements; end
  def initialize(*arg0); end
  def language; end
  def result; end
end
class Cucumber::Core::Gherkin::AstBuilder::BackgroundBuilder < Cucumber::Core::Gherkin::AstBuilder::Builder
  def children; end
  def initialize(*arg0); end
  def result(language); end
  def step_builders; end
  def steps(language); end
end
class Cucumber::Core::Gherkin::AstBuilder::ScenarioBuilder < Cucumber::Core::Gherkin::AstBuilder::Builder
  def children; end
  def initialize(*arg0); end
  def result(language); end
  def step_builders; end
  def steps(language); end
end
class Cucumber::Core::Gherkin::AstBuilder::StepBuilder < Cucumber::Core::Gherkin::AstBuilder::Builder
  def argument_builder(attributes); end
  def children; end
  def initialize(*arg0); end
  def multiline_argument; end
  def multiline_argument_builder; end
  def result(language); end
end
class Cucumber::Core::Gherkin::AstBuilder::OutlineStepBuilder < Cucumber::Core::Gherkin::AstBuilder::StepBuilder
  def result(language); end
end
class Cucumber::Core::Gherkin::AstBuilder::ScenarioOutlineBuilder < Cucumber::Core::Gherkin::AstBuilder::Builder
  def children; end
  def example_builders; end
  def examples(language); end
  def initialize(*arg0); end
  def result(language); end
  def step_builders; end
  def steps(language); end
end
class Cucumber::Core::Gherkin::AstBuilder::ExamplesTableBuilder < Cucumber::Core::Gherkin::AstBuilder::Builder
  def children; end
  def example_rows(language); end
  def example_rows_builders; end
  def header; end
  def header_builder; end
  def initialize(*arg0); end
  def result(language); end
end
class Cucumber::Core::Gherkin::AstBuilder::ExamplesTableBuilder::HeaderBuilder < Cucumber::Core::Gherkin::AstBuilder::Builder
  def result; end
end
class Cucumber::Core::Gherkin::AstBuilder::ExamplesTableBuilder::NullHeaderBuilder < Cucumber::Core::Gherkin::AstBuilder::Builder
  def initialize; end
  def result; end
end
class Cucumber::Core::Gherkin::AstBuilder::ExamplesTableBuilder::ExampleRowBuilder < Cucumber::Core::Gherkin::AstBuilder::Builder
  def result(language, header, index); end
end
class Cucumber::Core::Gherkin::AstBuilder::DataTableBuilder < Cucumber::Core::Gherkin::AstBuilder::Builder
  def location; end
  def result; end
  def rows; end
end
class Cucumber::Core::Gherkin::AstBuilder::DocStringBuilder < Cucumber::Core::Gherkin::AstBuilder::Builder
  def doc_string_location; end
  def result; end
end
class Cucumber::Core::Gherkin::ParseError < StandardError
end
class Cucumber::Core::Gherkin::Parser
  def document(document); end
  def done; end
  def event_bus; end
  def initialize(receiver, event_bus); end
  def receiver; end
end
class Cucumber::Core::Gherkin::Document
  def ==(other); end
  def body; end
  def initialize(uri, body, language = nil); end
  def language; end
  def to_s; end
  def uri; end
end
class Cucumber::Core::Gherkin::TagExpression
  def add(tags_with_negation_and_limits); end
  def empty?; end
  def evaluate(tags); end
  def initialize(tag_expressions); end
  def limits; end
  def ruby_expression; end
  def store_and_extract_limits(tags_with_negation_and_limits, negated); end
end
class Cucumber::Core::Test::Case
  def ==(other); end
  def all_locations; end
  def all_source; end
  def around_hooks; end
  def compose_around_hooks(visitor, *args, &block); end
  def describe_source_to(visitor, *args); end
  def describe_to(visitor, *args); end
  def eql?(other); end
  def feature; end
  def hash; end
  def initialize(test_steps, source, around_hooks = nil); end
  def inspect; end
  def keyword; end
  def language; end
  def location; end
  def match_locations?(queried_locations); end
  def match_name?(name_regexp); end
  def match_single_tag_expression?(expression); end
  def match_tags?(*expressions); end
  def name; end
  def old_style_tag_expression?(expression); end
  def source; end
  def step_count; end
  def tags; end
  def test_steps; end
  def with_around_hooks(around_hooks); end
  def with_steps(test_steps); end
end
class Cucumber::Core::Test::Case::NameBuilder
  def examples_table(table); end
  def examples_table_row(row); end
  def feature(*arg0); end
  def initialize(test_case); end
  def keyword; end
  def result; end
  def scenario(scenario); end
  def scenario_outline(outline); end
end
class Cucumber::Core::Test::Case::TagCollector
  def examples_table(node); end
  def examples_table_row(*arg0); end
  def feature(node); end
  def initialize(test_case); end
  def result; end
  def scenario(node); end
  def scenario_outline(node); end
end
class Cucumber::Core::Test::Timer
  def duration; end
  def nsec; end
  def sec; end
  def start; end
  def time_in_nanoseconds; end
end
module Cucumber::Core::Test::Timer::MonotonicTime
  def self.time_in_nanoseconds; end
  def time_in_nanoseconds; end
end
class Cucumber::Core::Test::Action
  def execute(*args); end
  def failed(exception); end
  def initialize(location = nil, &block); end
  def inspect; end
  def location; end
  def passed; end
  def skip(*arg0); end
  def skipped; end
end
class Cucumber::Core::Test::UnskippableAction < Cucumber::Core::Test::Action
  def skip(*args); end
end
class Cucumber::Core::Test::UndefinedAction
  def execute(*arg0); end
  def initialize(source_location); end
  def location; end
  def skip(*arg0); end
  def undefined; end
end
class Cucumber::Core::Test::Step
  def action_location; end
  def describe_source_to(visitor, *args); end
  def describe_to(visitor, *args); end
  def execute(*args); end
  def initialize(source, action = nil); end
  def inspect; end
  def location; end
  def original_location; end
  def skip(*args); end
  def source; end
  def text; end
  def to_s; end
  def with_action(location = nil, &block); end
end
class Cucumber::Core::Test::IsStepVisitor
  def initialize(test_step); end
  def method_missing(*arg0); end
  def step?; end
  def test_step(*arg0); end
end
class Cucumber::Core::Compiler
  def done; end
  def feature(feature); end
  def initialize(receiver); end
  def receiver; end
end
class Cucumber::Core::Compiler::TestCaseBuilder
  def background_test_steps; end
  def initialize(receiver); end
  def on_background_step(source); end
  def on_step(source); end
  def on_test_case(source); end
  def receiver; end
  def test_steps; end
end
class Cucumber::Core::Compiler::FeatureCompiler
  def background(background, &descend); end
  def feature(feature, &descend); end
  def initialize(receiver); end
  def receiver; end
  def scenario(scenario, &descend); end
  def scenario_outline(scenario_outline, &descend); end
end
class Cucumber::Core::Compiler::ScenarioOutlineCompiler
  def examples_table(examples_table, &descend); end
  def examples_table_row(row); end
  def initialize(source, receiver); end
  def outline_step(outline_step); end
  def outline_steps; end
  def receiver; end
  def source; end
  def steps(row); end
end
class Cucumber::Core::Compiler::ScenarioCompiler
  def initialize(source, receiver); end
  def receiver; end
  def source; end
  def step(step); end
end
class Cucumber::Core::Compiler::BackgroundCompiler
  def initialize(source, receiver); end
  def receiver; end
  def source; end
  def step(step); end
end
class Cucumber::Core::Test::Runner
  def around_hook(hook, &continue); end
  def done; end
  def event_bus; end
  def initialize(event_bus); end
  def running_test_case; end
  def running_test_step; end
  def test_case(test_case, &descend); end
  def test_step(test_step); end
end
class Cucumber::Core::Test::Runner::RunningTestCase
  def duration(step_duration, step_result); end
  def exception(step_exception, step_result); end
  def execute(test_step, &continue); end
  def failed(step_result); end
  def initialize; end
  def passed(step_result); end
  def pending(message, step_result); end
  def result; end
  def skipped(step_result); end
  def status; end
  def undefined(step_result); end
end
module Cucumber::Core::Test::Runner::RunningTestCase::Status
end
class Cucumber::Core::Test::Runner::RunningTestCase::Status::Base
  def execute(test_step, monitor, &continue); end
  def initialize(step_result); end
  def result; end
  def step_result; end
end
class Cucumber::Core::Test::Runner::RunningTestCase::Status::Unknown < Cucumber::Core::Test::Runner::RunningTestCase::Status::Base
  def result(duration); end
end
class Cucumber::Core::Test::Runner::RunningTestCase::Status::Passing < Cucumber::Core::Test::Runner::RunningTestCase::Status::Base
  def result(duration); end
end
class Cucumber::Core::Test::Runner::RunningTestCase::Status::Failing < Cucumber::Core::Test::Runner::RunningTestCase::Status::Base
  def execute(test_step, monitor, &continue); end
  def result(duration); end
end
class Cucumber::Core::Test::Runner::RunningTestCase::Status::Pending < Cucumber::Core::Test::Runner::RunningTestCase::Status::Failing
end
class Cucumber::Core::Test::Runner::RunningTestCase::Status::Skipping < Cucumber::Core::Test::Runner::RunningTestCase::Status::Failing
  def result(duration); end
end
class Cucumber::Core::Test::AroundHook
  def describe_to(visitor, *args, &continue); end
  def execute(*args, &continue); end
  def failed(exception); end
  def initialize(&block); end
end
module Cucumber::Core::Report
end
class Cucumber::Core::Report::Summary
  def initialize(event_bus); end
  def is_step?(test_step); end
  def ok?(be_strict = nil); end
  def subscribe_to(event_bus); end
  def test_cases; end
  def test_steps; end
end
class Cucumber::Core::Report::StepQueryVisitor
  def initialize(test_step); end
  def is_step?; end
  def method_missing(*arg0); end
  def step(*arg0); end
end
class Anonymous_Object_18
  def done; end
  def filter_locations; end
  def initialize(*args); end
  def receiver; end
  def test_case(test_case); end
  def with_receiver(new_receiver); end
end
class Cucumber::Core::Test::LocationsFilter < Anonymous_Object_18
  def done; end
  def sorted_test_cases; end
  def test_case(test_case); end
  def test_cases; end
end
class Anonymous_Object_19
  def done; end
  def initialize(*args); end
  def name_regexps; end
  def receiver; end
  def test_case(test_case); end
  def with_receiver(new_receiver); end
end
class Cucumber::Core::Test::NameFilter < Anonymous_Object_19
  def accept?(test_case); end
  def test_case(test_case); end
end
class Anonymous_Object_20
  def done; end
  def filter_expressions; end
  def initialize(*args); end
  def receiver; end
  def test_case(test_case); end
  def with_receiver(new_receiver); end
end
class Cucumber::Core::Test::TagFilter < Anonymous_Object_20
  def done; end
  def test_case(test_case); end
  def test_cases; end
end
class Cucumber::Core::Test::TagFilter::TestCases
  def <<(test_case); end
  def initialize; end
  def test_cases_by_tag_name; end
  def with_tag_name(tag_name); end
end
